language: go
sudo: required
dist: trusty
git:
  depth: 3

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
env:
  - TEST_SUITE=current      # go build
  - TEST_SUITE=unit         # go test
  - TEST_SUITE=integration  # go test -tags="integration"

matrix:
  exclude:
    - go: 1.5
      env: TEST_SUITE=integration
    - go: 1.6
      env: TEST_SUITE=integration
  include:
    - go: 1.8
      env: TEST_SUITE=pre-commit   # go vet, golint, go fmt
    - go: 1.8
      env: TEST_SUITE=coverprofile # go tests -coverprofile

before_install:
  - sudo apt-get install -y libpcap-dev
  - wget http://launchpadlibrarian.net/234454186/librdkafka1_0.8.6-1.1_amd64.deb
  - wget http://launchpadlibrarian.net/234454185/librdkafka-dev_0.8.6-1.1_amd64.deb
  - sudo dpkg -i librdkafka1_0.8.6-1.1_amd64.deb
  - sudo dpkg -i librdkafka-dev_0.8.6-1.1_amd64.deb
  - sudo apt-get install -y libsystemd-journal-dev
install:
  - go get github.com/mattn/goveralls

before_script:
  - GO15VENDOREXPERIMENT=1
script:
  - make $TEST_SUITE
after_success:
  - if [[ $TEST_SUITE == "coverprofile" ]]; then $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci; fi

notifications:
  slack:
    secure: CZ2AgNM8p5Xft82XBiN+jwm5j0TvqRapMr95Umfda1x4xv6trBQvyDwIqNcxKRWdQbS0KycF1m+WL7UI6HR/8Iq3LxLm2S7u3wAfK9GhTyt5aqL7qcfSPOtXm5qx42z9+HaAN7z+GWOuuVZTQUL5Jk0uMr2mhZRUpkmb+apji7YdHZf8tUXmHoVAomR/B6dKtcQg74nifX+d5zKCK2AY0u3KeJuOk+q8gmqWQnSJem3d4uKcyEp7zblE3IIuf6XzEw2KCBWeO8Lua7Mg/bWb8VjIRUjzluL6zn2ITd39jgk6L4Q1W1exj0KBLU04O1O8u+Y2KbUHqAMj9y8NpH0kiadAjV6IPE3AYbqm4ZcnsQzH/HnT/cjZ4Q8p+iOQMMzdoN1yKTKPDRZW4qnqftH4j5M06qBCO/DAmnXQlJkDRfTGy3tOhtpI89uYKi3X2ew3QWhV4aoboOs3oFZoSkU5GB6lW6xzmwVFZ3tjjCUOWD0ydypWmggPPUi0QbBsOgG3e8WLRGXdpt6Mpbt2YJuvTkwfe90fjFv/w6SkjV3H8vACXT25g04q3DP4q0xK0+9m4tDmhei3iVjFC6ut9xMXjHrnkJ2IT91lvTmbr5tCpJa86Rl4nIMqJe/HpdC6nVx3Pw663z7Q+wM/TEx0lfgf+4+63D4YyRZQo+yFy0noDQ8=
