
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.15.0"

[[constraint]]
  name = "github.com/abbot/go-http-auth"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/arbovm/levenshtein"

[[constraint]]
  branch = "master"
  name = "github.com/artyom/fb303"

[[constraint]]
  branch = "master"
  name = "github.com/artyom/scribe"

[[constraint]]
  branch = "master"
  name = "github.com/artyom/thrift"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.66"

[[constraint]]
  name = "github.com/bsm/sarama-cluster"
  version = "2.1.11"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "15.0.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.8.2"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/miekg/pcap"

[[constraint]]
  branch = "master"
  name = "github.com/mmcloughlin/geohash"

[[constraint]]
  name = "github.com/mssola/user_agent"
  version = "0.4.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/quipo/statsd"
  version = "1.4.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/trivago/grok"
  version = "1.0.0"

[[constraint]]
  name = "github.com/trivago/tgo"
  version = "1.0.3"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "0.5.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/mcuadros/go-syslog.v2"
  version = "2.2.1"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.62"

[[constraint]]
  name = "gopkg.in/oschwald/geoip2-golang.v1"
  version = "1.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
